name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain your problem.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the problem. Explicitly name key combinations you used to do things.
      placeholder: |
        For example:
        I used the key combination … to do…
  - type: input
    id: keyboard-layout
    attributes:
      label: Keyboard Layout
      description: You can find your active layout at `System Settings → Keyboard → Text Input → Input Sources`
      placeholder: "e.g.: ABC – QWERTZ"
    validations:
      required: true
  - type: input
    id: system-language
    attributes:
      label: System UI language
      description: You can find your active layout at `System Settings → General → Language & Region → Preferred Languages`. (The top language in the list, if there are multiple.)
      placeholder: "e.g.: English (US)"
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I updated to the latest version of this plugin.
          required: true
        - label: If I am using Alfred, I have activated its compatibility mode, as explained in the [Installation instructions of the README](..#installation).
          required: true
        - label: I updated to the latest version of Karabiner Elements.
          required: true
        - label: I have read about the limitations of Karabiner plugins in the [Caveats section of the README](..#caveats).
          required: true
